### ISSUE TITLE
Slack link on the website is not working

### ISSUE THREAD

**Issue by N-Saipraveen** [layer5io/slack#17]
#### Description

link on the website bottom leads to the attached screenshot 
#### Screenshots/Logs

<img width="836" alt="Screenshot 2023-09-17 at 9 52 47 PM" src="https://github.com/layer5io/slack/assets/113959118/baa57041-c5dc-480a-a57c-aea0b6be1554">

**Comment by toth2000** [comment]
Hey @N-Saipraveen , are you referring to the bottom footer of Layer5 website? 

As I have tested the link `https://slack.layer5.io/` is working fine.

<img width="960" alt="image" src="https://github.com/layer5io/slack/assets/65480420/c3bd011a-981b-4d22-a08f-fc9febe1462c">

**Comment by abhijeetgauravm** [comment]
hey @N-Saipraveen can u add the link and the page screenshot here where its not working.
